### ISSUE TITLE
Failed to set to the execution context

### ISSUE THREAD

**Issue by lingchingteng** [axodox/axodox-machinelearning#15]
Hi axodox,

I want to run the test, but all of the test results show "Failed to set to the execution context."

I have run update_dependencies.ps1 and build_nuget.ps1.

Did I miss something?

Thanks!

**Comment by axodox** [comment]
That is because Windows ships an old version of DirectML and ONNX runtime, and it is loaded instead the latest Nuget into the test runner. A workaround is to copy these files in the folder of the test runner.

However you will also need other input files and models to run the tests, which are currently not included in the repo due to their size, and GitHub LFS costs.
