### ISSUE TITLE
Access GPU data of result

### ISSUE THREAD

**Issue by syjeon121** [axodox/axodox-machinelearning#29]
@axodox hi, thank you for your work
I would like to use the GPU data of result image continuously without download to CPU.
How to access GPU data of txt2img result?

**Comment by axodox** [comment]
I have not tried it before, but the GetD3D12ResourceFromAllocation method of the OrtDmlApi class should allow you to get the underlying ID3D12Resource from an OrtValue. You also have methods to provide inputs as GPU resources. The drawback is since it is an execution provider specific API, you would closely couple your code to DML.

Since some operators in DML are CPU based, I am also not sure that it will bring the speed up you expect. I think for speeding up DML first we would have to increase the parallelism of the graph executor in it. As for me it seems that due to aggressive memory fencing only one node might execute at a time, reducing compute performance, where some of the GPU might go under utilized.

**Comment by syjeon121** [comment]
thank you for your advice. i will try :smile:
